[package]
name = "url-dispatch"
version = "1.0.0"
edition = "2018"
workspace = "../"

[dependencies]
ntex = { version = "0.6.5", features = ["tokio"] }
futures = "0.3.1"
openssl = "0.10"
serde = "1.0"
